project:
  type: website

website:
  title: "Home assignment2"
  navbar:
    left:
      - href: index.qmd
        text: Home
        menue:
          - href: source-1.qdm
            text: One
          - href: source-2.qdm
            text: Two
      - about.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



